project: Thesis
name: Skip Attention

parameters:
    model name: 'MultiScale1x1SkipAttention'
    model class: 'SkipAttentionModel'
    encoder type: 'gated'

    multiscale: True
    smoothness loss: False
    
    batch size: 8
    lr: 0.0001
    monitor: 'val_l1_full'
    epochs: 12
