project: Thesis
name: Skip Attention

parameters:
    model name: 'SkipAttention+MeanSmoothness'
    model class: 'SkipAttentionModel'
    encoder type: 'gated'

    multiscale: False
    smoothness loss: True
    lambda l1: 0.9
    lambda smooth: 0.1
    
    batch size: 8
    lr: 0.0001
    monitor: 'val_l1_depth_loss'
    epochs: 12
