project: Thesis
name: Skip Attention

parameters:
    model name: 'DualEncoderSkipnetEdgeWithMultiscale1x1'
    model class: 'SkipNetModel'
    encoder type: 'gated'
    use edges: True
    single encoder: False

    multiscale: True
    smoothness loss: False
    
    batch size: 8
    lr: 0.0001
    monitor: 'val_l1_full'
    epochs: 12
