project: Thesis
name: Skip Attention

parameters:
    model name: 'DualEncoderSkipnetEdge+MeanSmoothness'
    model class: 'SkipNetModel'
    encoder type: 'gated'
    single encoder: False
    use edges: True
    concat rgb: False

    multiscale: False
    smoothness loss: True
    lambda l1: 0.9
    lambda smooth: 0.1
    
    batch size: 8
    lr: 0.0001
    monitor: 'val_l1_depth_loss'
    epochs: 12
