project: Thesis
name: Skip Attention

parameters:
    model name: 'SkipAttentionSmooth'
    model class: 'SkipAttentionModel'
    encoder type: 'gated'

    multiscale: False
    smoothness loss: True
    
    batch size: 8
    lr: 0.0001
    monitor: 'val_l1_depth_loss'
    epochs: 12