project: Thesis
name: Edge Attention

parameters:
    model name: 'EdgeAttentionModelPretrainBCE'
    model class: 'EdgeAttentionModel'
    encoder type: 'gated'

    lambda depth: 0.6
    lambda edge: 0.4
    batch size: 8
    lr: 0.0001
    monitor: 'val_l1_depth_loss'
    epochs: 12
