project: Thesis
name: Skipnet baseline

parameters:
    model name: "MaskedRGBSingleEncoderSkipNet"
    model class: "SkipNetModel"
    encoder type: "gated"
    single encoder: True
    multiscale: False
    smoothness loss: False
    concat rgb: False
    masked rgb: True

    use edges: False

    batch size: 8
    lr: 0.0001
    monitor: "val_l1_depth_loss"
    epochs: 12
