project: Thesis
name: Skipnet baseline

parameters:
    model name: "SingleEncoderSkipNetWithEdge"
    model class: "SkipNetModel"
    encoder type: "gated"
    single encoder: True
    use edges: True

    batch size: 8
    lr: 0.0001
    monitor: "val_l1_depth_loss"
    epochs: 12
