project: Thesis
name: Skipnet baseline

parameters:
    model name: "SkipNetWithRGBEdges"
    model class: "SkipNetModel"
    encoder type: "gated"
    single encoder: False

    use edges: True
    concat rgb: True
    multiscale: False
    smoothness loss: False

    batch size: 8
    lr: 0.0001
    monitor: "val_l1_depth_loss"
    epochs: 12
