project: Thesis
name: Single encoder

parameters:
    model name: "Depth2DeptInitialModel"
    model class: "InitialModel"
    encoder type: "gated"

    rgb input: 'no'

    batch size: 4
    lr: 0.0001
    monitor: "val_l1_depth_loss"
    epochs: 5