project: Thesis
name: Single encoder

parameters:
    model name: "ChannelWiseInitialModel"
    model class: "InitialModel"
    encoder type: "base"

    rgb input: 'channelwise'

    batch size: 8
    lr: 0.0001
    monitor: "val_l1_depth_loss"
    epochs: 5
