project: Thesis
name: Gated baseline

parameters:
    model name: "GatedBaselineRGBEdge"
    model class: "BaselineModel"
    encoder type: "gated"
    batch size: 8
    lr: 0.0001
    monitor: "val_l1_depth_loss"
    epochs: 8
    concat edge: 'rgb'
